version: '3.8'
networks:
  prometheus:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana-prometheus.yml:/etc/grafana/provisioning/datasources/grafana-prometheus.yml
    networks:
      -  prometheus
    ports:
      - 3000:3000
